### ISSUE TITLE
get error when i "make clean Build"

### ISSUE THREAD

**Issue by OmarDez** [pulp-platform/pulpissimo#75] opened 2019-09-04 17:43 UTC
I get an error message when I "make clean build" in the building rtl platform stage, I have uploaded screenshot of this error.

Regards.
![Pulpissimo_error](https://user-images.githubusercontent.com/46606066/64278061-7a9cc980-cf11-11e9-9046-5d77f87b54eb.png)

**Comment by bluewww** [comment] 2019-09-04 18:13
Did you run `./generate_scripts` before calling `make`?

**Comment by OmarDez** [comment] 2019-09-04 18:20
yes, I first run `./update-ips`, and after that  `./generate-scripts`, but it displays an error

**Comment by OmarDez** [comment] 2019-09-04 18:53
> yes, I first run `./update-ips`, and after that `./generate-scripts`, but it displays an error

Gives the same error

**Comment by ranaya123** [comment] 2019-09-10 17:34
Hi, I can reproduce the same error when building Pulpissimo platform with pulp-sdk (not pulp-builder). 
**ERROR: there are unallowed keys for ip 'fpu_div_sqrt_mvp', sub-ip 'div_sqrt_top_mvp':**

This is the ./update-ips output :
https://pastebin.com/KPEfTZHC

This is same for master branch as well as newer versions of Pulpissimo (i.e. v4). What could possibly go wrong here ?

**Comment by bluewww** [comment] 2019-09-10 17:41
These are recent patches that added more entries to the `src_files.yml` for other tools. I'm not sure if this is the cause of the breakage your experiencing.

**Comment by OmarDez** [comment] 2019-09-10 17:47
How can I install correctly the system?

**Comment by bluewww** [comment] 2019-09-10 17:49
It looks like your issue is related to this one. It is this PR https://github.com/pulp-platform/fpnew/pull/18 from yesterday.

**Comment by bluewww** [comment] 2019-09-10 17:55
Ok I can reproduce both errors, I will try to fix it asap (most likely tomorrow).

**Comment by OmarDez** [comment] 2019-09-10 17:57
Thanks very much, I´ll wait for the fix
Regards.

**Comment by ranaya123** [comment] 2019-09-11 08:10
@OmarDez : If you want a quick fix and get the rtl simulations up and running with Modelsim, change the "generate_script" file content to following (This was in-fact the old gen script) :
https://pastebin.com/0RWQdm2b

As @bluewww , stated the issue stems from the new stuffs/support added to the generate script.

**Comment by bluewww** [comment] 2019-09-11 11:21
Fixed in https://github.com/pulp-platform/IPApproX/commit/7c356b29d8f3a8c06b326dbadd269907503b9348.

**Comment by OmarDez** [comment] 2019-09-11 16:21
Sorry for the question, do I have to clone everything again and install everything in order for the changes to take place?

**Comment by OmarDez** [comment] 2019-09-11 16:52
@ranaya123 I change the "generate_Script" file but the error continues.
@bluewww Do I have to install everything from the begining ? I have updated the pulpissimo folder and followed the steps of `./update-ips`  and `./generate-scripts`, but it gives me the same error.
Thanks

**Comment by bluewww** [comment] 2019-09-11 17:05
Unfortunately ipstools is not very smart. Its best if you clone and run the scripts again. If you don't want to do that you can try to delete ipstools in the folder.

**Comment by OmarDez** [comment] 2019-09-11 17:27
The scripts run correctly and clone the file with the updated code, but the same error message when I run `make clean build` continues, is the same as the screen shot I uploaded before.

**Comment by bluewww** [comment] 2019-09-11 17:48
I can't reproduce your problem. I run these commands
```
git clone https://github.com/pulp-platform/pulpissimo/
cd pulpissimo
./update-ips
make clean build

```

**Comment by OmarDez** [comment] 2019-09-11 18:02
@bluewww I run the commands you write and gives me the error,.
I add you a screen shot when I run `./scripts/build-runtime` is this the expected result? 
![image](https://user-images.githubusercontent.com/46606066/64722351-e93ed180-d493-11e9-8bc6-81745a56ef2e.png)
After that I run these commands:
`source sdk-setup.sh`
`source configs/rtl.sh`
`cd ..`
`cd pulpissimo`
`./update-ips`
`make clean build`
and gives me error

**Comment by FrancescoConti** [comment] 2019-09-11 18:20
These keys have been added by a PULP partner for another project, but apparently they break compatibility for some people. We are currently working to fix this — in the mean time the workaround is to go inside the offending ips in `ips/ip_name` and remove all the section with `jg*` references.

**Comment by bluewww** [comment] 2019-09-11 18:51
@FrancescoConti this is already fixed, see my previous comments

**Comment by OmarDez** [comment] 2019-09-11 20:45
@bluewww  I also have this error while installing SDK
![image](https://user-images.githubusercontent.com/46606066/64733860-22cf0700-d4ab-11e9-85ca-790e19b94de8.png)
Thanks

**Comment by OmarDez** [comment] 2019-09-12 03:44
I tried to build the SDK with `make all` in two different computer and it showed the same error "Permission denied (publickey)" I tried to install PULP in another computer but I couldn't build the SDK, is there a solution for this??
Thanks. Regards.

**Comment by OmarDez** [comment] 2019-09-12 03:48
this is the screen shot ![Screenshot from 2019-09-11 22-47-36](https://user-images.githubusercontent.com/46606066/64752735-3d72a180-d4e6-11e9-8826-9f16fd67d635.png)
Regards.

**Comment by ranaya123** [comment] 2019-09-12 07:58
@OmarDez : Those errors are related to your public ssh key of github. If you followed the steps for pulp-sdk build, then the build should work !
Thanks @bluewww for the quick fix !

**Comment by bluewww** [comment] 2020-01-27 23:41
Looks solved. Please reopen if needed.

**Closed by bluewww** 2020-01-27 23:41 UTC
